const express = require("express")
const bodyParser = require("body-parser")
const mongodb = require("mongoose")
const routes = require("./routes/routes")
const app = express()
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))
mongodb.connect("mongodb+srv://disha123:hl6LMcJIED1eCZhr@cluster0.hrerz.mongodb.net/luciaMongodbAdapter")
    .then(() => { console.log("mongodb is connected") })
    .catch((error) => { console.log(error.message) })
app.use("/", routes)
app.listen(process.env.PORT || 4000, function () {
    console.log("express is running on the port ", + (process.env.PORT || 4000))
})
